#include "op_lookup.h"

#include <stdio.h>
#include <stdlib.h>

#include "load_instructions.h"
#include "alu_instructions.h"
#include "op/cb_lookup.h"
#include "branch_instructions.h"
#include "op/instruction_result.h"

struct InstructionResult op_invalid(struct State* state)
{
	printf("Instruction is invalid: $%02x\n", read_pc(state));
	exit(1);
}

struct InstructionResult op_not_implemented(struct State* state)
{
	printf("Unknown instruction: $%02x\n", read_pc(state));
	exit(1);
}

// Initialize lookup table with function pointers
struct OpDefinition op_lookup[256] = {
	[0x00] = { "NOP", 1, op_not_implemented },
	[0x01] = { "LD BC, $%04x", 3, op_not_implemented },
	[0x02] = { "LD (BC), A", 1, op_not_implemented },
	[0x03] = { "INC BC", 1, op_not_implemented },
	[0x04] = { "INC B", 1, op_not_implemented },
	[0x05] = { "DEC B", 1, op_not_implemented },
	[0x06] = { "LD B, $%02x", 2, op_not_implemented },
	[0x07] = { "RLCA", 1, op_not_implemented },
	[0x08] = { "LD ($%04x), SP", 3, op_not_implemented },
	[0x09] = { "ADD HL, BC", 1, op_not_implemented },
	[0x0a] = { "LD A, (BC)", 1, op_not_implemented },
	[0x0b] = { "DEC BC", 1, op_not_implemented },
	[0x0c] = { "INC C", 1, op_not_implemented },
	[0x0d] = { "DEC C", 1, op_not_implemented },
	[0x0e] = { "LD C, $%02x", 2, op_ld_c_u8 },
	[0x0f] = { "RRCA", 1, op_not_implemented },
	[0x10] = { "STOP", 1, op_not_implemented },
	[0x11] = { "LD DE, $%04x", 3, op_not_implemented },
	[0x12] = { "LD (DE), A", 1, op_not_implemented },
	[0x13] = { "INC DE", 1, op_not_implemented },
	[0x14] = { "INC D", 1, op_not_implemented },
	[0x15] = { "DEC D", 1, op_not_implemented },
	[0x16] = { "LD D, $%02x", 2, op_not_implemented },
	[0x17] = { "RLA", 1, op_not_implemented },
	[0x18] = { "JR $%02x", 2, op_not_implemented },
	[0x19] = { "ADD HL, DE", 1, op_not_implemented },
	[0x1a] = { "LD A, (DE)", 1, op_not_implemented },
	[0x1b] = { "DEC DE", 1, op_not_implemented },
	[0x1c] = { "INC E", 1, op_not_implemented },
	[0x1d] = { "DEC E", 1, op_not_implemented },
	[0x1e] = { "LD E, $%02x", 2, op_not_implemented },
	[0x1f] = { "RRA", 1, op_not_implemented },
	[0x20] = { "JR NZ, $%02x", 2, op_jr_nz_i8 },
	[0x21] = { "LD HL, $%04x", 3, op_ld_hl_u16 },
	[0x22] = { "LD (HL+), A", 1, op_not_implemented },
	[0x23] = { "INC HL", 1, op_not_implemented },
	[0x24] = { "INC H", 1, op_not_implemented },
	[0x25] = { "DEC H", 1, op_not_implemented },
	[0x26] = { "LD H, $%02x", 2, op_not_implemented },
	[0x27] = { "DAA", 1, op_not_implemented },
	[0x28] = { "JR Z, $%02x", 2, op_not_implemented },
	[0x29] = { "ADD HL, HL", 1, op_not_implemented },
	[0x2a] = { "LD A, (HL+)", 1, op_not_implemented },
	[0x2b] = { "DEC HL", 1, op_not_implemented },
	[0x2c] = { "INC L", 1, op_not_implemented },
	[0x2d] = { "DEC L", 1, op_not_implemented },
	[0x2e] = { "LD L, $%02x", 2, op_not_implemented },
	[0x2f] = { "CPL", 1, op_not_implemented },
	[0x30] = { "JR NC, $%02x", 2, op_not_implemented },
	[0x31] = { "LD SP, $%04x", 3, op_ld_sp_u16 },
	[0x32] = { "LD (HL-), A", 1, op_ld_hld_a },
	[0x33] = { "INC SP", 1, op_not_implemented },
	[0x34] = { "INC (HL)", 1, op_not_implemented },
	[0x35] = { "DEC (HL)", 1, op_not_implemented },
	[0x36] = { "LD (HL), $%02x", 2, op_not_implemented },
	[0x37] = { "SCF", 1, op_not_implemented },
	[0x38] = { "JR C, $%02x", 2, op_not_implemented },
	[0x39] = { "ADD HL, SP", 1, op_not_implemented },
	[0x3a] = { "LD A, (HL-)", 1, op_not_implemented },
	[0x3b] = { "DEC SP", 1, op_not_implemented },
	[0x3c] = { "INC A", 1, op_not_implemented },
	[0x3d] = { "DEC A", 1, op_not_implemented },
	[0x3e] = { "LD A, $%02x", 2, op_ld_a_u8 },
	[0x3f] = { "CCF", 1, op_not_implemented },
	[0x40] = { "LD B, B", 1, op_not_implemented },
	[0x41] = { "LD B, C", 1, op_not_implemented },
	[0x42] = { "LD B, D", 1, op_not_implemented },
	[0x43] = { "LD B, E", 1, op_not_implemented },
	[0x44] = { "LD B, H", 1, op_not_implemented },
	[0x45] = { "LD B, L", 1, op_not_implemented },
	[0x46] = { "LD B, (HL)", 1, op_not_implemented },
	[0x47] = { "LD B, A", 1, op_not_implemented },
	[0x48] = { "LD C, B", 1, op_not_implemented },
	[0x49] = { "LD C, C", 1, op_not_implemented },
	[0x4a] = { "LD C, D", 1, op_not_implemented },
	[0x4b] = { "LD C, E", 1, op_not_implemented },
	[0x4c] = { "LD C, H", 1, op_not_implemented },
	[0x4d] = { "LD C, L", 1, op_not_implemented },
	[0x4e] = { "LD C, (HL)", 1, op_not_implemented },
	[0x4f] = { "LD C, A", 1, op_not_implemented },
	[0x50] = { "LD D, B", 1, op_not_implemented },
	[0x51] = { "LD D, C", 1, op_not_implemented },
	[0x52] = { "LD D, D", 1, op_not_implemented },
	[0x53] = { "LD D, E", 1, op_not_implemented },
	[0x54] = { "LD, D, H", 1, op_not_implemented },
	[0x55] = { "LD D, L", 1, op_not_implemented },
	[0x56] = { "LD D, (HL)", 1, op_not_implemented },
	[0x57] = { "LD D, A", 1, op_not_implemented },
	[0x58] = { "LD E, B", 1, op_not_implemented },
	[0x59] = { "LD E, C", 1, op_not_implemented },
	[0x5a] = { "LD E, D", 1, op_not_implemented },
	[0x5b] = { "LD E, E", 1, op_not_implemented },
	[0x5c] = { "LD E, H", 1, op_not_implemented },
	[0x5d] = { "LD E, L", 1, op_not_implemented },
	[0x5e] = { "LD E, (HL)", 1, op_not_implemented },
	[0x5f] = { "LD E, A", 1, op_not_implemented },
	[0x60] = { "LD H, B", 1, op_not_implemented },
	[0x61] = { "LD H, C", 1, op_not_implemented },
	[0x62] = { "LD H, D", 1, op_not_implemented },
	[0x63] = { "LD H, E", 1, op_not_implemented },
	[0x64] = { "LD H, H", 1, op_not_implemented },
	[0x65] = { "LD H, L", 1, op_not_implemented },
	[0x66] = { "LD H, (HL)", 1, op_not_implemented },
	[0x67] = { "LD H, A", 1, op_not_implemented },
	[0x68] = { "LD L, B", 1, op_not_implemented },
	[0x69] = { "LD L, C", 1, op_not_implemented },
	[0x6a] = { "LD L, D", 1, op_not_implemented },
	[0x6b] = { "LD L, E", 1, op_not_implemented },
	[0x6c] = { "LD L, H", 1, op_not_implemented },
	[0x6d] = { "LD L, L", 1, op_not_implemented },
	[0x6e] = { "LD LD L, (HL)", 1, op_not_implemented },
	[0x6f] = { "LD L, A", 1, op_not_implemented },
	[0x70] = { "LD (HL), B", 1, op_not_implemented },
	[0x71] = { "LD (HL), C", 1, op_not_implemented },
	[0x72] = { "LD (HL), D", 1, op_not_implemented },
	[0x73] = { "LD (HL), E", 1, op_not_implemented },
	[0x74] = { "LD (HL), H", 1, op_not_implemented },
	[0x75] = { "LD (HL), L", 1, op_not_implemented },
	[0x76] = { "HALT", 1, op_not_implemented },
	[0x77] = { "LD (HL), A", 1, op_not_implemented },
	[0x78] = { "LD A, B", 1, op_not_implemented },
	[0x79] = { "LD A, C", 1, op_not_implemented },
	[0x7a] = { "LD A, D", 1, op_not_implemented },
	[0x7b] = { "LD A, E", 1, op_not_implemented },
	[0x7c] = { "LD A, H", 1, op_not_implemented },
	[0x7d] = { "LD A, L", 1, op_not_implemented },
	[0x7e] = { "LD A, (HL)", 1, op_not_implemented },
	[0x7f] = { "LD A, A", 1, op_not_implemented },
	[0x80] = { "ADD A, B", 1, op_not_implemented },
	[0x81] = { "ADD A, C", 1, op_not_implemented },
	[0x82] = { "ADD A, D", 1, op_not_implemented },
	[0x83] = { "ADD A, E", 1, op_not_implemented },
	[0x84] = { "ADD A, H", 1, op_not_implemented },
	[0x85] = { "ADD A, L", 1, op_not_implemented },
	[0x86] = { "ADD A, (HL)", 1, op_not_implemented },
	[0x87] = { "ADD A, A", 1, op_not_implemented },
	[0x88] = { "ADC A, B", 1, op_not_implemented },
	[0x89] = { "ADC A, C", 1, op_not_implemented },
	[0x8a] = { "ADC A, D", 1, op_not_implemented },
	[0x8b] = { "ADC A, E", 1, op_not_implemented },
	[0x8c] = { "ADC A, H", 1, op_not_implemented },
	[0x8d] = { "ADC A, L", 1, op_not_implemented },
	[0x8e] = { "ADC A, (HL)", 1, op_not_implemented },
	[0x8f] = { "ADC A, A", 1, op_not_implemented },
	[0x90] = { "SUB A, B", 1, op_not_implemented },
	[0x91] = { "SUB A, C", 1, op_not_implemented },
	[0x92] = { "SUB A, D", 1, op_not_implemented },
	[0x93] = { "SUB A, E", 1, op_not_implemented },
	[0x94] = { "SUB A, H", 1, op_not_implemented },
	[0x95] = { "SUB A, L", 1, op_not_implemented },
	[0x96] = { "SUB A, (HL)", 1, op_not_implemented },
	[0x97] = { "SUB A, A", 1, op_not_implemented },
	[0x98] = { "SBC A, B", 1, op_not_implemented },
	[0x99] = { "SBC A, C", 1, op_not_implemented },
	[0x9a] = { "SBC A, D", 1, op_not_implemented },
	[0x9b] = { "SBC A, E", 1, op_not_implemented },
	[0x9c] = { "SBC A, H", 1, op_not_implemented },
	[0x9d] = { "SBC A, L", 1, op_not_implemented },
	[0x9e] = { "SBC A, (HL)", 1, op_not_implemented },
	[0x9f] = { "SBC A, A", 1, op_not_implemented },
	[0xa0] = { "AND A, B", 1, op_not_implemented },
	[0xa1] = { "AND A, C", 1, op_not_implemented },
	[0xa2] = { "AND A, D", 1, op_not_implemented },
	[0xa3] = { "AND A, E", 1, op_not_implemented },
	[0xa4] = { "AND A, H", 1, op_not_implemented },
	[0xa5] = { "AND A, L", 1, op_not_implemented },
	[0xa6] = { "AND A, (HL)", 1, op_not_implemented },
	[0xa7] = { "AND A, A", 1, op_not_implemented },
	[0xa8] = { "XOR A, B", 1, op_not_implemented },
	[0xa9] = { "XOR A, C", 1, op_not_implemented },
	[0xaa] = { "XOR A, D", 1, op_not_implemented },
	[0xab] = { "XOR A, E", 1, op_not_implemented },
	[0xac] = { "XOR A, H", 1, op_not_implemented },
	[0xad] = { "XOR A, L", 1, op_not_implemented },
	[0xae] = { "XOR A, (HL)", 1, op_not_implemented },
	[0xaf] = { "XOR A, A", 1, op_xor_a_a },
	[0xb0] = { "OR A, B", 1, op_not_implemented },
	[0xb1] = { "OR A, C", 1, op_not_implemented },
	[0xb2] = { "OR A, D", 1, op_not_implemented },
	[0xb3] = { "OR A, E", 1, op_not_implemented },
	[0xb4] = { "OR A, H", 1, op_not_implemented },
	[0xb5] = { "OR A, L", 1, op_not_implemented },
	[0xb6] = { "OR A, (HL)", 1, op_not_implemented },
	[0xb7] = { "OR A, A", 1, op_not_implemented },
	[0xb8] = { "CP A, B", 1, op_not_implemented },
	[0xb9] = { "CP A, C", 1, op_not_implemented },
	[0xba] = { "CP A, D", 1, op_not_implemented },
	[0xbb] = { "CP A, E", 1, op_not_implemented },
	[0xbc] = { "CP A, H", 1, op_not_implemented },
	[0xbd] = { "CP A, L", 1, op_not_implemented },
	[0xbe] = { "CP A, (HL)", 1, op_not_implemented },
	[0xbf] = { "CP A, A", 1, op_not_implemented },
	[0xc0] = { "RET NZ", 1, op_not_implemented },
	[0xc1] = { "POP BC", 1, op_not_implemented },
	[0xc2] = { "JP NZ, $%04x", 3, op_not_implemented },
	[0xc3] = { "JP $%04x", 3, op_not_implemented },
	[0xc4] = { "CALL NZ, $%04x", 3, op_not_implemented },
	[0xc5] = { "PUSH BC", 1, op_not_implemented },
	[0xc6] = { "ADD A, $%02x", 2, op_not_implemented },
	[0xc7] = { "RST 00h", 1, op_not_implemented },
	[0xc8] = { "RET Z", 1, op_not_implemented },
	[0xc9] = { "RET", 1, op_not_implemented },
	[0xca] = { "JP Z, $%04x", 3, op_not_implemented },
	[0xcb] = { .callback = op_invalid }, // PREFIX CB
	[0xcc] = { "CALL Z, $%04x", 3, op_not_implemented },
	[0xcd] = { "CALL $%04x", 3, op_not_implemented },
	[0xce] = { "ADC A, $%02x", 2, op_not_implemented },
	[0xcf] = { "RST 08h", 1, op_not_implemented },
	[0xd0] = { "RET NC", 1, op_not_implemented },
	[0xd1] = { "POP DE", 1, op_not_implemented },
	[0xd2] = { "JP NC, $%04x", 3, op_not_implemented },
	[0xd3] = { .callback = op_invalid }, // NONE
	[0xd4] = { "CALL NC, $%04x", 3, op_not_implemented },
	[0xd5] = { "PUSH DE", 1, op_not_implemented },
	[0xd6] = { "SUB A, $%02x", 2, op_not_implemented },
	[0xd7] = { "RST 10h", 1, op_not_implemented },
	[0xd8] = { "RET C", 1, op_not_implemented },
	[0xd9] = { "RETI", 1, op_not_implemented },
	[0xda] = { "JP C, $%04x", 3, op_not_implemented },
	[0xdb] = { .callback = op_invalid }, // NONE
	[0xdc] = { "CALL C, $%04x", 3, op_not_implemented },
	[0xdd] = { .callback = op_invalid }, // NONE
	[0xde] = { "SBC A, $%02x", 2, op_not_implemented },
	[0xdf] = { "RST 18h", 1, op_not_implemented },
	[0xe0] = { "LD (FF00+$%02x), A", 2, op_not_implemented },
	[0xe1] = { "POP HL", 1, op_not_implemented },
	[0xe2] = { "LD (FF00+C), A", 1, op_ld_ff00_plus_c_a },
	[0xe3] = { .callback = op_invalid }, // NONE
	[0xe4] = { .callback = op_invalid }, // NONE
	[0xe5] = { "PUSH HL", 1, op_not_implemented },
	[0xe6] = { "AND A, $%02x", 2, op_not_implemented },
	[0xe7] = { "RST 20h", 1, op_not_implemented },
	[0xe8] = { "ADD SP, $%02x", 2, op_not_implemented },
	[0xe9] = { "JP HL", 1, op_not_implemented },
	[0xea] = { "LD ($%04x), A", 3, op_not_implemented },
	[0xeb] = { .callback = op_invalid }, // NONE
	[0xec] = { .callback = op_invalid }, // NONE
	[0xed] = { .callback = op_invalid }, // NONE
	[0xee] = { "XOR A, $%02x", 2, op_not_implemented },
	[0xef] = { "RST 28h", 1, op_not_implemented },
	[0xf0] = { "LD A, (FF00+$%02x)", 2, op_not_implemented },
	[0xf1] = { "POP AF", 1, op_not_implemented },
	[0xf2] = { "LD A, (FF00+C)", 1, op_not_implemented },
	[0xf3] = { "DI", 1, op_not_implemented },
	[0xf4] = { .callback = op_invalid }, // NONE
	[0xf5] = { "PUSH AF", 1, op_not_implemented },
	[0xf6] = { "OR A, $%02x", 2, op_not_implemented },
	[0xf7] = { "RST 30h", 1, op_not_implemented },
	[0xf8] = { "LD HL, SP+$%02x", 2, op_not_implemented },
	[0xf9] = { "LD SP, HL", 1, op_not_implemented },
	[0xfa] = { "LD A, ($%04x)", 3, op_not_implemented },
	[0xfb] = { "EI", 1, op_not_implemented },
	[0xfc] = { .callback = op_invalid }, // NONE
	[0xfd] = { .callback = op_invalid }, // NONE
	[0xfe] = { "CP A, $%02x", 2, op_not_implemented },
	[0xff] = { "RST 38h", 1, op_not_implemented },
};

struct OpDefinition decode(struct State* state, uint8_t pos)
{
	if (read_char(state, pos) == 0xcb) {
		return cb_decode(state, pos + 1);
	}
	return op_lookup[read_char(state, pos)];
}

